### ISSUE TITLE
Different behavior during switching from window mode to fullscreen by 2 methods

### ISSUE THREAD

**Issue by filux** [MegaGlest/megaglest-source#71]
presuppositions:
- screen resolution in MG set to 640x480,
- MG start in window mode,
- OS/desktop resolution set to 1280x1024.

1. Changing mode from window to fullscreen in options 
= fullscreen with res 1280x1024.

2. Changing mode from window to fullscreen by alt + enter 
= fullscreen with res 640x480.

**Comment by filux** [comment]
Since c402509 situation in 2. case is much worse, now screen area is buggy. But this commit had possitive (I think) effect for #77.

![notfullscreen3](https://cloud.githubusercontent.com/assets/5335953/10522532/f41b532c-7375-11e5-984a-d9a1dc0bd0b3.png)

**Comment by filux** [comment]
on 81346ba situation is the same (bad) as previously ^ checked.

**Comment by softcoder** [comment]
Which OS and architecture, linux 64?

**Comment by filux** [comment]
yep, linux x64, debian testing
imo not bad idea is to use this "auto res change" code also for second method

**Comment by softcoder** [comment]
Please try this now it should be fixed

**Comment by filux** [comment]
yep, this is fixed :) but I found something new related (minor thing but may be a bit confusing).


presuppositions:
- OS/desktop resolution set to 1280x1024.
- screen resolution in MG set to 640x480 and enabled fullscreen mode (checked in glestuser.ini)


MG start (fullscreen and auto change to 640x480>1280x1024, so is ok) >
Changing mode from fullscreen to window by alt + enter >
= window with res 1280x1024 (expected window with res 640x480 because this is saved in glestuser.ini).

**Comment by softcoder** [comment]
You mentioned: MG start (fullscreen and auto change to 640x480>1280x1024, so is ok) 

That means you saved a new resolution, so that is why its using this. I see no bug here.

**Comment by filux** [comment]
> That means you saved a new resolution, so that is why its using this.

Hehe. Yep "saved" resolution value in some "cache" and "lost" previous value from window mode and in settings all the time is 640x480, so this is a bit confusing. 
Imo it is just confusing and most likely not fast will be bug report about this so if it is too minor problem vs fixing effort then this may be left as it is :).

Another example, mostly just commands and pictures:
- Settings:
```
$ cat ~/.megaglest/glestuser.ini | grep -e 'ScreenWidth=' -e 'ScreenHeight=' -e 'Windowed='
   ScreenHeight=480
   ScreenWidth=640
   Windowed=0
```
- now launch by ```./megaglest --resolution=640x480 --fullscreen=true``` (or just ```./megaglest```, same settings and same result)
```
./megaglest
   megaglest v3.12-dev
   Compiled using: GNUC: 50201 [64bit] on: Oct 29 2015 10:03:52 platform: Linux-X64 endianness: little
   GIT: [Rev: 5209.b83fab2] - using STREFLOP [SSE] - [no-denormals]
   Forcing resolution [640x480]
   Forcing fullscreen [true]
   Auto Change resolution to (1280 x 1024) from (640 x 480)
   MainWindow forced change of resolution to desktop values (1280 x 1024) instead of (640 x 480)
```
 - alt + enter
 - result (window mode but **not** with res 640x480)
```
xwininfo -name MegaGlest | grep geometry
  -geometry 1280x1024+0+0
```
![wrongwindowsize](https://cloud.githubusercontent.com/assets/5335953/10848569/e0d5e158-7f1c-11e5-9f10-f1cbf466230c.png)
- Again checked settings (nothing changed):
```
$ kill -9 `pidof megaglest`
$ cat ~/.megaglest/glestuser.ini | grep -e 'ScreenWidth=' -e 'ScreenHeight=' -e 'Windowed='
   ScreenHeight=480
   ScreenWidth=640
   Windowed=0
```
 - expected result, same like after ```./megaglest --resolution=640x480 --fullscreen=false``` > alt+ enter > alt + enter > check 
![wrongwindowsize1](https://cloud.githubusercontent.com/assets/5335953/10848631/3b258870-7f1d-11e5-8f38-2c65d8681338.png)

**Comment by titiger** [comment]
The main problem is, we have no idea how to handle full screen resolutions in sdl2 yet. The only fullscreen mode that works is "as Desktop" . But there must be a way to fix this because there are other games using SDL2 who can do this. I would not change the whole behaviour meanwhile to "fix" somehting that is still broken. I like the current state softcoder made and thats good enough until we find the real fix for the SDL fullscreen problem.

**Comment by filux** [comment]
Heh but this method "as Desktop" seems to be very good, by this we dropped few problems with fullscreen which were present also in sdl1. Seems like now fullscreen as default setting is safe to keep set and you will not brake your OS-monitor-resolution configuration by launching Mg with this which was previously pretty common.  
... so basically if there will not be problems/bug reports negatively related with "auto res change" (e.g. in case multi monitor configurations) then I believe more for that other projects will "steal" this idea from MG than for this finding and insertion of something better :D

**Comment by softcoder** [comment]
I think we should just leave it as its working now since sdl2 seems to not have better support for fullscreen than what we see in the current code. In another release of SDL we can revisit.
